on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build and Test with PostgreSQL and RabbitMQ
    runs-on: ubuntu-latest # Alterado para Ubuntu para melhor compatibilidade com serviços de container

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: techuser
          POSTGRES_PASSWORD: techpassword
          POSTGRES_DB: DddTestDb
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U techuser" 
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      rabbitmq:
        image: rabbitmq:3-management
        ports:
          - 5672:5672 # Porta do RabbitMQ
          - 15672:15672 # Porta do Management UI
        options: >-
          --health-cmd "rabbitmq-diagnostics -q ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build -c Debug

      - name: Test with the dotnet CLI
        env:
          ASPNETCORE_ENVIRONMENT: "Development"
          ConnectionStrings__DefaultConnection: "Host=localhost;Database=DddTestDb;Username=techuser;Password=techpassword"
          RabbitMQ__HostName: "localhost"
          RabbitMQ__UserName: "guest"
          RabbitMQ__Password: "guest"
        run: dotnet test -c Debug
